import os
import tempfile
import shutil
import zipfile
from unittest.mock import patch
import pytest

import simple_coding_agent

from test_utils.grounding_verifier import GroundingVerifier


def run_automated_readme_test(input_queue, zip_file_path, repo_name, max_calls_limit=30):
    """
    Custom runner for the /readme macro that extracts a zipped repository
    into a temporary sandbox, allowing the agent to analyze it and write a README.
    """
    print("🧪 Starting Automated Agent Flow Test for /readme...", flush=True)

    original_cwd = os.getcwd()
    test_sandbox = tempfile.mkdtemp(prefix="agent_readme_sandbox_")
    print(f"📁 Created temporary sandbox at: {test_sandbox}", flush=True)

    # --- Extract the ZIP file into the sandbox ---
    source_zip_path = os.path.abspath(os.path.join(original_cwd, zip_file_path))
    if not os.path.exists(source_zip_path):
        shutil.rmtree(test_sandbox)
        pytest.fail(f"Real target zip file not found at: {source_zip_path}")

    with zipfile.ZipFile(source_zip_path, 'r') as zip_ref:
        zip_ref.extractall(test_sandbox)

    print(f"🌱 Extracted {zip_file_path} into sandbox.", flush=True)

    # --- Direct State Injection ---
    simple_coding_agent.session_cwd = test_sandbox
    simple_coding_agent.FORCE_TESTING = True

    safety_counter = {"calls": 0, "max_calls": max_calls_limit}

    def smart_input_mocker(prompt=""):
        safety_counter["calls"] += 1
        if safety_counter["calls"] > safety_counter["max_calls"]:
            print("\n🛑 [Test Overload] Too many input calls. Forcing exit.", flush=True)
            return "/quit"

        prompt_str = str(prompt).lower()

        # Catch tool approvals (e.g., allowing write_file for README.md)
        if "allow" in prompt_str or "y/n" in prompt_str:
            print("\n🤖 [Automated Test] Auto-approving tool execution: 'y'", flush=True)
            return "y"

        # Consume from the queue
        if input_queue:
            next_input = input_queue.pop(0)
            print(f"\n⌨️  [Automated Test] Typing: {next_input}", flush=True)
            return next_input

        # Default fallback if queue is exhausted but agent is still prompting
        return "/quit"

    try:
        # Move agent execution into the sandbox
        os.chdir(test_sandbox)

        with patch("builtins.input", side_effect=smart_input_mocker):
            try:
                simple_coding_agent.main()
            except SystemExit as e:
                print(f"\n🏁 Agent terminated with code: {e.code}", flush=True)

        # --- Phase 1: Generation Results ---
        print("\n" + "=" * 60, flush=True)
        print("📊 Phase 1: Readme Generation Verification", flush=True)

        # Ensure the agent generated the README.md in the current directory
        readme_path = os.path.join(test_sandbox, repo_name + "/README.md")

        if os.path.exists(readme_path):
            print("✅ SUCCESS: README.md was generated.", flush=True)

            # --- Phase 2: Content Sanity Check ---
            print("\n" + "=" * 60, flush=True)
            print("🕵️  Phase 2: Content Sanity Check", flush=True)

            file_size = os.path.getsize(readme_path)
            with open(readme_path, "r", encoding="utf-8") as f:
                content = f.read()

            print(f"README Size: {file_size} bytes", flush=True)

            if file_size > 50:  # Basic check to ensure it's not empty or just a title
                print("✅ Content length check passed.")
            else:
                pytest.fail("README.md was generated but appears empty or too short!")

            # Optional semantic check based on the known zip context
            if "minesweeper" in content.lower():
                print("✅ Contextual check passed (Found target keyword).")
            else:
                print("⚠️ NOTICE: The word 'Minesweeper' wasn't in the README, check the prompt tuning.")

        else:
            pytest.fail("README.md was not generated by the agent!")

    finally:
        # --- Cleanup ---
        os.chdir(original_cwd)
        shutil.rmtree(test_sandbox)
        print(f"\n🧹 Cleaned up temporary sandbox.", flush=True)


def test_agent_readme_generation():
    """
    Tests the /readme macro by extracting a sample repo and running the agent on it.
    """
    zip_target = "test_data/minesweeper-solve.zip"

    repo_name = "minesweeper-solve"
    input_queue = [
        # Execute the macro on the current sandbox directory
        "/readme ./" + repo_name,
        "/send",

        # Provide closure to the LLM to end its tool-calling loop (just in case)
        "Looks good, task complete.",
        "/send",

        # Trigger graceful exit
        "/quit"
    ]

    # Max calls limit increased slightly in case it uses read_file tools to inspect code first
    run_automated_readme_test(
        input_queue=input_queue,
        zip_file_path=zip_target,
        repo_name=repo_name,
        max_calls_limit=40
    )

def test_agent_readme_generation_deep():
    """
    Tests the /readme macro by extracting a sample repo and running the agent on it.
    """
    zip_target = "test_data/minesweeper-solve.zip"

    repo_name = "minesweeper-solve"
    input_queue = [
        # Execute the macro on the current sandbox directory
        "/readme --deep ./" + repo_name,
        "/send",

        # Provide closure to the LLM to end its tool-calling loop (just in case)
        "Looks good, task complete.",
        "/send",

        # Trigger graceful exit
        "/quit"
    ]

    # Max calls limit increased slightly in case it uses read_file tools to inspect code first
    run_automated_readme_test(
        input_queue=input_queue,
        zip_file_path=zip_target,
        repo_name=repo_name,
        max_calls_limit=40
    )

def prepare_self_repo_sandbox(target_dir):
    """
    Copies the current repository into a sandbox, ignoring cache and git history.
    """
    ignore_patterns = shutil.ignore_patterns(
        ".git", ".venv", "venv", "env", "__pycache__",
        ".idea", ".vscode", "dist", "build", ".pytest_cache", "models", "README.md",
    )
    # Copy current workspace into a subfolder inside the temporary sandbox
    repo_dest = os.path.join(target_dir, "simple-coding-agent")
    shutil.copytree(os.getcwd(), repo_dest, ignore=ignore_patterns)
    return repo_dest

def run_automated_self_readme_test(input_queue, repo_name, mode_flag, expected_keywords=None):
    """
    Custom runner that dynamically snapshots the live repository into a sandbox for self-testing.
    """
    print(f"🧪 Starting Live Self-Test for /readme {mode_flag}...", flush=True)

    original_cwd = os.getcwd()
    test_sandbox = tempfile.mkdtemp(prefix="agent_self_readme_sandbox_")

    try:
        # Dynamically copy current repo into sandbox
        prepare_self_repo_sandbox(test_sandbox)

        simple_coding_agent.session_cwd = test_sandbox
        simple_coding_agent.FORCE_TESTING = True

        safety_counter = {"calls": 0, "max_calls": 40}

        def smart_input_mocker(prompt=""):
            safety_counter["calls"] += 1
            if safety_counter["calls"] > safety_counter["max_calls"]:
                return "/quit"

            prompt_str = str(prompt).lower()
            if "allow" in prompt_str or "y/n" in prompt_str:
                return "y"

            if input_queue:
                return input_queue.pop(0)

            return "/quit"

        os.chdir(test_sandbox)

        with patch("builtins.input", side_effect=smart_input_mocker):
            try:
                simple_coding_agent.main()
            except SystemExit:
                pass

        # Verification metrics
        readme_path = os.path.join(test_sandbox, repo_name, "README.md")
        if not os.path.exists(readme_path):
            pytest.fail("README.md was not generated for the live agent codebase!")

        with open(readme_path, "r", encoding="utf-8") as f:
            content = f.read()

        word_count = len(content.split())
        print(f"📊 Self-README Word Count ({mode_flag}): {word_count} words", flush=True)

        if word_count < 150:
            pytest.fail(f"README is too shallow ({word_count} words).")

        if expected_keywords:
            missing = [kw for kw in expected_keywords if kw.lower() not in content.lower()]
            if missing:
                pytest.fail(f"README missing expected keywords: {missing}")

    finally:
        os.chdir(original_cwd)
        shutil.rmtree(test_sandbox)

def test_self_readme_generation_deep():
    """
    Tests /readme --deep against the current live state of the agent codebase.
    """
    input_queue = [
        "/readme --deep ./simple-coding-agent", "/send",
        "Looks good, task complete.", "/send", "/quit"
    ]
    # Pass direct_repo_copy=True instead of a zip path
    run_automated_self_readme_test(
        input_queue=input_queue,
        repo_name="simple-coding-agent",
        mode_flag="--deep",
        expected_keywords=["agent"]
    )

def test_self_readme_generation_deep_ast():
    """
    Tests /readme --deep-ast against the current live state of the agent codebase.
    """
    input_queue = [
        "/readme --deep-ast ./simple-coding-agent", "/send",
        "Looks good, task complete.", "/send", "/quit"
    ]
    run_automated_self_readme_test(
        input_queue=input_queue,
        repo_name="simple-coding-agent",
        mode_flag="--deep-ast",
        expected_keywords=["agent"]
    )


def run_readme_and_capture(zip_file_path, repo_name, mode_flag):
    """Modified runner that returns the README content instead of asserting."""
    original_cwd = os.getcwd()
    test_sandbox = tempfile.mkdtemp(prefix=f"benchmark_{mode_flag.strip('-')}_")

    source_zip_path = os.path.abspath(os.path.join(original_cwd, zip_file_path))
    with zipfile.ZipFile(source_zip_path, 'r') as zip_ref:
        zip_ref.extractall(test_sandbox)

    simple_coding_agent.session_cwd = test_sandbox
    simple_coding_agent.FORCE_TESTING = True

    input_queue = [
        f"/readme {mode_flag} ./{repo_name}", "/send",
        "Looks good, task complete.", "/send", "/quit"
    ]

    safety_counter = {"calls": 0, "max": 40}

    def mocker(prompt=""):
        safety_counter["calls"] += 1
        if safety_counter["calls"] > safety_counter["max"]: return "/quit"
        p = str(prompt).lower()
        if "allow" in p or "y/n" in p: return "y"
        return input_queue.pop(0) if input_queue else "/quit"

    try:
        os.chdir(test_sandbox)
        with patch("builtins.input", side_effect=mocker):
            try:
                simple_coding_agent.main()
            except SystemExit:
                pass

        readme_path = os.path.join(test_sandbox, repo_name, "README.md")
        if os.path.exists(readme_path):
            with open(readme_path, "r", encoding="utf-8") as f:
                return f.read()
        return ""
    finally:
        os.chdir(original_cwd)
        shutil.rmtree(test_sandbox)


def test_minesweeper_macro_benchmark():
    """
    Pilots the benchmark comparison between --deep and --deep-ast
    on the Minesweeper repository (generating both READMEs in a sandbox and comparing
    their quality with GroundingVerifier).
    """
    zip_target = "test_data/minesweeper-solve.zip"
    repo_name = "minesweeper-solve"

    print("\n" + "=" * 60)
    print("🚀 STARTING BENCHMARK: --deep vs --deep-ast")
    print("=" * 60)

    # 1. Setup Ground Truth Verifier
    original_cwd = os.getcwd()
    ground_truth_sandbox = tempfile.mkdtemp(prefix="ground_truth_")
    source_zip_path = os.path.abspath(os.path.join(original_cwd, zip_target))

    with zipfile.ZipFile(source_zip_path, 'r') as zip_ref:
        zip_ref.extractall(ground_truth_sandbox)

    verifier = GroundingVerifier(os.path.join(ground_truth_sandbox, repo_name))

    try:
        # 2. Run both modes and capture output
        print("\n⏳ Running agent with --deep...")
        readme_deep = run_readme_and_capture(zip_target, repo_name, "--deep")

        print("⏳ Running agent with --deep-ast...")
        readme_ast = run_readme_and_capture(zip_target, repo_name, "--deep-ast")

        # 3. Evaluate
        score_deep = verifier.evaluate_readme(readme_deep)
        score_ast = verifier.evaluate_readme(readme_ast)

        # 4. Print Report (Run pytest with '-s' flag to see this!)
        print("\n" + "=" * 60)
        print("📊 MINESWEEPER BENCHMARK REPORT")
        print("=" * 60)

        print("Mode [--deep]:")
        print(f"  • Groundedness Precision: {score_deep['groundedness_score']}%")
        print(f"  • Info Density:           {score_deep['density_score']}")
        print(f"  • Suspected Hallucinations:\n    {score_deep['hallucination_candidates']}")

        print("\nMode [--deep-ast]:")
        print(f"  • Groundedness Precision: {score_ast['groundedness_score']}%")
        print(f"  • Info Density:           {score_ast['density_score']}")
        print(f"  • Suspected Hallucinations:\n    {score_ast['hallucination_candidates']}")
        print("=" * 60)

        # Soft asserts just to ensure the test passes if generation worked
        assert len(readme_deep) > 50, "--deep failed to generate meaningful text"
        assert len(readme_ast) > 50, "--deep-ast failed to generate meaningful text"

    finally:
        shutil.rmtree(ground_truth_sandbox)


def run_self_readme_and_capture(repo_name, mode_flag):
    """
    Modified runner for the live repository that returns the README content
    for benchmarking instead of asserting immediately.
    """
    original_cwd = os.getcwd()
    test_sandbox = tempfile.mkdtemp(prefix=f"benchmark_self_{mode_flag.strip('-')}_")

    try:
        # Dynamically copy current repo into sandbox
        prepare_self_repo_sandbox(test_sandbox)

        simple_coding_agent.session_cwd = test_sandbox
        simple_coding_agent.FORCE_TESTING = True

        input_queue = [
            f"/readme {mode_flag} ./{repo_name}", "/send",
            "Looks good, task complete.", "/send", "/quit"
        ]

        # Bumped max calls to 80 for the larger repository
        safety_counter = {"calls": 0, "max": 80}

        def mocker(prompt=""):
            safety_counter["calls"] += 1
            if safety_counter["calls"] > safety_counter["max"]: return "/quit"
            p = str(prompt).lower()
            if "allow" in p or "y/n" in p: return "y"
            return input_queue.pop(0) if input_queue else "/quit"

        os.chdir(test_sandbox)
        with patch("builtins.input", side_effect=mocker):
            try:
                simple_coding_agent.main()
            except SystemExit:
                pass

        readme_path = os.path.join(test_sandbox, repo_name, "README.md")
        if os.path.exists(readme_path):
            with open(readme_path, "r", encoding="utf-8") as f:
                return f.read()
        return ""
    finally:
        os.chdir(original_cwd)
        shutil.rmtree(test_sandbox)


def test_self_macro_benchmark():
    """
    Pilots the benchmark comparison between --deep and --deep-ast
    on the live Simple Coding Agent repository to measure performance on a larger codebase.
    """
    repo_name = "simple-coding-agent"

    print("\n" + "=" * 60)
    print("🚀 STARTING SELF-REPO BENCHMARK: --deep vs --deep-ast")
    print("=" * 60)

    # 1. Setup Ground Truth Verifier from the live codebase
    original_cwd = os.getcwd()
    ground_truth_sandbox = tempfile.mkdtemp(prefix="ground_truth_self_")

    # Copy current workspace into the ground truth sandbox
    prepare_self_repo_sandbox(ground_truth_sandbox)
    verifier = GroundingVerifier(os.path.join(ground_truth_sandbox, repo_name))

    try:
        # 2. Run both modes and capture output
        print("\n⏳ Running agent with --deep (Line-by-Line Regex)...")
        readme_deep = run_self_readme_and_capture(repo_name, "--deep")

        print("⏳ Running agent with --deep-ast (AST Structure/Signatures)...")
        readme_ast = run_self_readme_and_capture(repo_name, "--deep-ast")

        # 3. Evaluate using the verifier
        score_deep = verifier.evaluate_readme(readme_deep)
        score_ast = verifier.evaluate_readme(readme_ast)

        # 4. Print Report (Run pytest with '-s' flag to see this!)
        print("\n" + "=" * 60)
        print("📊 SELF-REPO BENCHMARK REPORT (AGENT CODEBASE)")
        print("=" * 60)

        print("Mode [--deep]:")
        print(f"  • Groundedness Precision: {score_deep['groundedness_score']}%")
        print(f"  • Info Density:           {score_deep['density_score']}")
        print(f"  • Total Code References:  {score_deep['total_code_references']}")
        print(f"  • Suspected Hallucinations:\n    {score_deep['hallucination_candidates']}")

        print("\nMode [--deep-ast]:")
        print(f"  • Groundedness Precision: {score_ast['groundedness_score']}%")
        print(f"  • Info Density:           {score_ast['density_score']}")
        print(f"  • Total Code References:  {score_ast['total_code_references']}")
        print(f"  • Suspected Hallucinations:\n    {score_ast['hallucination_candidates']}")
        print("=" * 60)

        # Soft asserts to ensure generations actually fired
        assert len(readme_deep) > 50, "--deep failed to generate meaningful text on self-repo"
        assert len(readme_ast) > 50, "--deep-ast failed to generate meaningful text on self-repo"

    finally:
        shutil.rmtree(ground_truth_sandbox)
